HALF_IRONMAN_POLARIZED_TEMPLATE = [
    {"week": 1, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 45, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Running - Endurance Run", "duration": 35, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 40, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 60, "intensity_zone": "Z2"},
    ]},
    {"week": 2, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 50, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Running - Endurance Run", "duration": 35, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Swimming - Endurance Base", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 30, "intensity_zone": "Z5"},
        {"type": "Brick - Bike + Run", "duration": 55, "intensity_zone": "Z2"},
    ]},
    {"week": 3, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 50, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 48, "intensity_zone": "Z2"},
        {"type": "Running - Endurance Run", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 48, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 75, "intensity_zone": "Z2"},
    ]},
    {"week": 4, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 45, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 34, "intensity_zone": "Z2"},
        {"type": "Running - Endurance Run", "duration": 30, "intensity_zone": "Z2"},
        {"type": "Cycling - Recovery Ride", "duration": 30, "intensity_zone": "Z1"},
        {"type": "Swimming - Endurance Base", "duration": 41, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 30, "intensity_zone": "Z5"},
        {"type": "Cycling - Endurance Ride", "duration": 45, "intensity_zone": "Z2"},
    ]},
    {"week": 5, "sessions": [
        {"type": "Cycling - Hill Sprints", "duration": 55, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 39, "intensity_zone": "Z5"},
        {"type": "Cycling - Endurance Ride", "duration": 90, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 55, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 90, "intensity_zone": "Z2"},
    ]},
    {"week": 6, "sessions": [
        {"type": "Cycling - Hill Sprints", "duration": 60, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 54, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 42, "intensity_zone": "Z5"},
        {"type": "Cycling - Endurance Ride", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Swimming - Time Trial", "duration": 48, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 60, "intensity_zone": "Z2"},
    ]},
    {"week": 7, "sessions": [
        {"type": "Cycling - Hill Sprints", "duration": 65, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 58, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 42, "intensity_zone": "Z5"},
        {"type": "Cycling - Endurance Ride", "duration": 105, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 60, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 105, "intensity_zone": "Z2"},
    ]},
    {"week": 8, "sessions": [
        {"type": "Cycling - Hill Sprints", "duration": 55, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 43, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 39, "intensity_zone": "Z5"},
        {"type": "Cycling - Recovery Ride", "duration": 45, "intensity_zone": "Z1"},
        {"type": "Swimming - Endurance Base", "duration": 55, "intensity_zone": "Z2"},
        {"type": "Running - Endurance Run", "duration": 35, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 60, "intensity_zone": "Z2"},
    ]},
    {"week": 9, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 60, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 35, "intensity_zone": "Z5"},
        {"type": "Cycling - Endurance Ride", "duration": 120, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 62, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 120, "intensity_zone": "Z2"},
    ]},
    {"week": 10, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 60, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 63, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 35, "intensity_zone": "Z5"},
        {"type": "Cycling - Endurance Ride", "duration": 90, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 65, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 80, "intensity_zone": "Z2"},
    ]},
    {"week": 11, "sessions": [
        {"type": "Cycling - Hill Sprints", "duration": 65, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 65, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 40, "intensity_zone": "Z5"},
        {"type": "Cycling - Endurance Ride", "duration": 135, "intensity_zone": "Z2"},
        {"type": "Swimming - Time Trial", "duration": 74, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 65, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 135, "intensity_zone": "Z2"},
    ]},
    {"week": 12, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 60, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 48, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 35, "intensity_zone": "Z5"},
        {"type": "Cycling - Recovery Ride", "duration": 60, "intensity_zone": "Z1"},
        {"type": "Swimming - Endurance Base", "duration": 55, "intensity_zone": "Z2"},
        {"type": "Running - Endurance Run", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Triathlon - Sprint", "duration": 60, "intensity_zone": "Z5"},
    ]},
    {"week": 13, "sessions": [
        {"type": "Cycling - Hill Sprints", "duration": 70, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 65, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 40, "intensity_zone": "Z5"},
        {"type": "Cycling - Endurance Ride", "duration": 150, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 72, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 70, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 150, "intensity_zone": "Z2"},
    ]},
    {"week": 14, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 75, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 68, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 40, "intensity_zone": "Z5"},
        {"type": "Cycling - Endurance Ride", "duration": 105, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 72, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 105, "intensity_zone": "Z2"},
    ]},
    {"week": 15, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 60, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 72, "intensity_zone": "Z2"},
        {"type": "Running - Race Pace", "duration": 36, "intensity_zone": "Z4"},
        {"type": "Cycling - Endurance Ride", "duration": 165, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 72, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 80, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 165, "intensity_zone": "Z2"},
    ]},
    {"week": 16, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 55, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 55, "intensity_zone": "Z2"},
        {"type": "Running - Race Pace", "duration": 34, "intensity_zone": "Z4"},
        {"type": "Cycling - Recovery Ride", "duration": 60, "intensity_zone": "Z1"},
        {"type": "Swimming - Endurance Base", "duration": 48, "intensity_zone": "Z2"},
        {"type": "Running - Endurance Run", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Triathlon - Olympic", "duration": 120, "intensity_zone": "Z4"},
    ]},
    {"week": 17, "sessions": [
        {"type": "Cycling - Hill Sprints", "duration": 65, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 72, "intensity_zone": "Z2"},
        {"type": "Running - VO2max Intervals", "duration": 40, "intensity_zone": "Z5"},
        {"type": "Cycling - Endurance Ride", "duration": 180, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 72, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 90, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 180, "intensity_zone": "Z2"},
    ]},
    {"week": 18, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 70, "intensity_zone": "Z5"},
        {"type": "Swimming - Time Trial", "duration": 86, "intensity_zone": "Z5"},
        {"type": "Running - Race Pace", "duration": 38, "intensity_zone": "Z4"},
        {"type": "Cycling - Endurance Ride", "duration": 150, "intensity_zone": "Z2"},
        {"type": "Swimming - Endurance Base", "duration": 72, "intensity_zone": "Z2"},
        {"type": "Running - Endurance Run", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 150, "intensity_zone": "Z2"},
    ]},
    {"week": 19, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 75, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 72, "intensity_zone": "Z2"},
        {"type": "Running - Race Pace", "duration": 40, "intensity_zone": "Z4"},
        {"type": "Cycling - Endurance Ride", "duration": 135, "intensity_zone": "Z2"},
        {"type": "Swimming - Sprint Intervals", "duration": 72, "intensity_zone": "Z5"},
        {"type": "Running - Endurance Run", "duration": 65, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 135, "intensity_zone": "Z2"},
    ]},
    {"week": 20, "sessions": [
        {"type": "Cycling - VO2max Intervals", "duration": 60, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 58, "intensity_zone": "Z2"},
        {"type": "Running - Race Pace", "duration": 32, "intensity_zone": "Z4"},
        {"type": "Cycling - Recovery Ride", "duration": 45, "intensity_zone": "Z1"},
        {"type": "Swimming - Sprint Intervals", "duration": 38, "intensity_zone": "Z5"},
        {"type": "Swimming - Endurance Base", "duration": 38, "intensity_zone": "Z2"},
        {"type": "Race - Half Ironman", "duration": 300, "intensity_zone": "Z4"},
    ]},
]
