"""
Full Ironman 140.6 — Balanced variant, 30 weeks.
Based on Matt Fitzgerald 80/20 principles and standard IM periodization.
Zone distribution: mixed intensity (Z2 base, Z3/Z4 tempo, Z5 intervals).
"""

IRONMAN_BALANCED_TEMPLATE = [
    # === BASE PHASE: Weeks 1–10 ===
    # Build aerobic foundation. 80% Z2, introduce discipline variety.
    {"week": 1, "sessions": [
        {"type": "Swimming - Technique Drills", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 35, "intensity_zone": "Z2"},
        {"type": "Swimming - Continuous", "duration": 35, "intensity_zone": "Z2"},
        {"type": "Cycling - Easy Ride", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 40, "intensity_zone": "Z2"},
    ]},
    {"week": 2, "sessions": [
        {"type": "Swimming - Technique Drills", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 90, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Swimming - Continuous", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Cycling - Easy Ride", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Running - Long Run", "duration": 60, "intensity_zone": "Z2"},
    ]},
    {"week": 3, "sessions": [
        {"type": "Swimming - Technique Drills", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 100, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Swimming - Continuous", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Cycling - Easy Ride", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Running - Long Run", "duration": 70, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 75, "intensity_zone": "Z2", "optional": True},
    ]},
    {"week": 4, "sessions": [
        {"type": "Swimming - Easy Swim", "duration": 35, "intensity_zone": "Z1"},
        {"type": "Cycling - Recovery Ride", "duration": 60, "intensity_zone": "Z1"},
        {"type": "Running - Recovery Run", "duration": 30, "intensity_zone": "Z1"},
        {"type": "Swimming - Continuous", "duration": 35, "intensity_zone": "Z2"},
        {"type": "Cycling - Easy Ride", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 40, "intensity_zone": "Z2"},
    ]},
    {"week": 5, "sessions": [
        {"type": "Swimming - Intervals", "duration": 45, "intensity_zone": "Z3"},
        {"type": "Cycling - Endurance Ride", "duration": 105, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Swimming - Continuous", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Cycling - Easy Ride", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Running - Long Run", "duration": 75, "intensity_zone": "Z2"},
    ]},
    {"week": 6, "sessions": [
        {"type": "Swimming - Intervals", "duration": 50, "intensity_zone": "Z3"},
        {"type": "Cycling - Endurance Ride", "duration": 120, "intensity_zone": "Z2"},
        {"type": "Running - Tempo Run", "duration": 35, "intensity_zone": "Z3"},
        {"type": "Swimming - Continuous", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 90, "intensity_zone": "Z2"},
        {"type": "Running - Long Run", "duration": 80, "intensity_zone": "Z2"},
    ]},
    {"week": 7, "sessions": [
        {"type": "Swimming - Intervals", "duration": 50, "intensity_zone": "Z3"},
        {"type": "Cycling - Long Ride", "duration": 135, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Swimming - Continuous", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Cycling - Tempo Ride", "duration": 60, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 90, "intensity_zone": "Z2"},
    ]},
    {"week": 8, "sessions": [
        {"type": "Swimming - Easy Swim", "duration": 35, "intensity_zone": "Z1"},
        {"type": "Cycling - Recovery Ride", "duration": 60, "intensity_zone": "Z1"},
        {"type": "Running - Recovery Run", "duration": 30, "intensity_zone": "Z1"},
        {"type": "Swimming - Continuous", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Cycling - Easy Ride", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 45, "intensity_zone": "Z2"},
    ]},
    {"week": 9, "sessions": [
        {"type": "Swimming - Intervals", "duration": 55, "intensity_zone": "Z3"},
        {"type": "Cycling - Long Ride", "duration": 150, "intensity_zone": "Z2"},
        {"type": "Running - Tempo Run", "duration": 40, "intensity_zone": "Z3"},
        {"type": "Swimming - Continuous", "duration": 55, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 100, "intensity_zone": "Z2"},
        {"type": "Running - Long Run", "duration": 100, "intensity_zone": "Z2"},
    ]},
    {"week": 10, "sessions": [
        {"type": "Swimming - Intervals", "duration": 55, "intensity_zone": "Z3"},
        {"type": "Cycling - Long Ride", "duration": 165, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Swimming - Continuous", "duration": 55, "intensity_zone": "Z2"},
        {"type": "Cycling - Tempo Ride", "duration": 75, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 110, "intensity_zone": "Z2"},
    ]},
    # === BUILD 1: Weeks 11–15 ===
    # Introduce threshold intervals. Long rides 2.5h+. Brick sessions.
    {"week": 11, "sessions": [
        {"type": "Swimming - Threshold Sets", "duration": 55, "intensity_zone": "Z4"},
        {"type": "Cycling - Long Ride", "duration": 165, "intensity_zone": "Z2"},
        {"type": "Running - Threshold Run", "duration": 40, "intensity_zone": "Z4"},
        {"type": "Swimming - Continuous", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 120, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 120, "intensity_zone": "Z2"},
    ]},
    {"week": 12, "sessions": [
        {"type": "Swimming - Threshold Sets", "duration": 60, "intensity_zone": "Z4"},
        {"type": "Cycling - Long Ride", "duration": 180, "intensity_zone": "Z2"},
        {"type": "Running - Intervals", "duration": 35, "intensity_zone": "Z5"},
        {"type": "Swimming - Continuous", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Cycling - Threshold Ride", "duration": 60, "intensity_zone": "Z4"},
        {"type": "Running - Long Run", "duration": 130, "intensity_zone": "Z2"},
    ]},
    {"week": 13, "sessions": [
        {"type": "Swimming - Easy Swim", "duration": 40, "intensity_zone": "Z1"},
        {"type": "Cycling - Recovery Ride", "duration": 60, "intensity_zone": "Z1"},
        {"type": "Running - Recovery Run", "duration": 30, "intensity_zone": "Z1"},
        {"type": "Swimming - Continuous", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Cycling - Easy Ride", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 50, "intensity_zone": "Z2"},
    ]},
    {"week": 14, "sessions": [
        {"type": "Swimming - Threshold Sets", "duration": 60, "intensity_zone": "Z4"},
        {"type": "Cycling - Long Ride", "duration": 195, "intensity_zone": "Z2"},
        {"type": "Running - Threshold Run", "duration": 45, "intensity_zone": "Z4"},
        {"type": "Swimming - Continuous", "duration": 65, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 135, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 140, "intensity_zone": "Z2"},
    ]},
    {"week": 15, "sessions": [
        {"type": "Swimming - Threshold Sets", "duration": 65, "intensity_zone": "Z4"},
        {"type": "Cycling - Long Ride", "duration": 210, "intensity_zone": "Z2"},
        {"type": "Running - Intervals", "duration": 40, "intensity_zone": "Z5"},
        {"type": "Swimming - Continuous", "duration": 65, "intensity_zone": "Z2"},
        {"type": "Cycling - Threshold Ride", "duration": 60, "intensity_zone": "Z4"},
        {"type": "Running - Long Run", "duration": 150, "intensity_zone": "Z2"},
    ]},
    # === DELOAD: Week 16 ===
    {"week": 16, "sessions": [
        {"type": "Swimming - Easy Swim", "duration": 40, "intensity_zone": "Z1"},
        {"type": "Cycling - Recovery Ride", "duration": 75, "intensity_zone": "Z1"},
        {"type": "Running - Recovery Run", "duration": 35, "intensity_zone": "Z1"},
        {"type": "Swimming - Continuous", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Cycling - Easy Ride", "duration": 90, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 50, "intensity_zone": "Z2"},
    ]},
    # === BUILD 2: Weeks 17–22 ===
    # Race-pace work. Long rides 4h+. Long run 2.5h+. Brick sessions weekly.
    {"week": 17, "sessions": [
        {"type": "Swimming - Race Pace Sets", "duration": 65, "intensity_zone": "Z4"},
        {"type": "Cycling - Long Ride", "duration": 225, "intensity_zone": "Z2"},
        {"type": "Running - Tempo Run", "duration": 50, "intensity_zone": "Z3"},
        {"type": "Swimming - Continuous", "duration": 65, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 150, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 150, "intensity_zone": "Z2"},
    ]},
    {"week": 18, "sessions": [
        {"type": "Swimming - Race Pace Sets", "duration": 65, "intensity_zone": "Z4"},
        {"type": "Cycling - Long Ride", "duration": 240, "intensity_zone": "Z2"},
        {"type": "Running - Threshold Run", "duration": 50, "intensity_zone": "Z4"},
        {"type": "Swimming - Continuous", "duration": 70, "intensity_zone": "Z2"},
        {"type": "Cycling - Race Simulation", "duration": 90, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 155, "intensity_zone": "Z2"},
    ]},
    {"week": 19, "sessions": [
        {"type": "Swimming - Easy Swim", "duration": 40, "intensity_zone": "Z1"},
        {"type": "Cycling - Recovery Ride", "duration": 90, "intensity_zone": "Z1"},
        {"type": "Running - Recovery Run", "duration": 35, "intensity_zone": "Z1"},
        {"type": "Swimming - Continuous", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Cycling - Easy Ride", "duration": 90, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 55, "intensity_zone": "Z2"},
    ]},
    {"week": 20, "sessions": [
        {"type": "Swimming - Race Pace Sets", "duration": 70, "intensity_zone": "Z4"},
        {"type": "Cycling - Long Ride", "duration": 255, "intensity_zone": "Z2"},
        {"type": "Running - Tempo Run", "duration": 55, "intensity_zone": "Z3"},
        {"type": "Swimming - Continuous", "duration": 70, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 165, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 160, "intensity_zone": "Z2"},
    ]},
    {"week": 21, "sessions": [
        {"type": "Swimming - Race Pace Sets", "duration": 70, "intensity_zone": "Z4"},
        {"type": "Cycling - Long Ride", "duration": 270, "intensity_zone": "Z2"},
        {"type": "Running - Intervals", "duration": 45, "intensity_zone": "Z5"},
        {"type": "Swimming - Continuous", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Cycling - Race Simulation", "duration": 90, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 160, "intensity_zone": "Z2"},
    ]},
    {"week": 22, "sessions": [
        {"type": "Swimming - Race Pace Sets", "duration": 70, "intensity_zone": "Z4"},
        {"type": "Cycling - Long Ride", "duration": 270, "intensity_zone": "Z2"},
        {"type": "Running - Threshold Run", "duration": 55, "intensity_zone": "Z4"},
        {"type": "Swimming - Continuous", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Brick - Bike + Run", "duration": 180, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 165, "intensity_zone": "Z2"},
    ]},
    # === PEAK: Weeks 23–25 ===
    # Highest fitness. Race simulation weekend. Peak TSS.
    {"week": 23, "sessions": [
        {"type": "Swimming - Race Simulation", "duration": 75, "intensity_zone": "Z3"},
        {"type": "Cycling - Race Simulation Ride", "duration": 285, "intensity_zone": "Z3"},
        {"type": "Running - Race Pace Run", "duration": 55, "intensity_zone": "Z4"},
        {"type": "Swimming - Continuous", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Brick - Race Simulation", "duration": 195, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 165, "intensity_zone": "Z2"},
    ]},
    {"week": 24, "sessions": [
        {"type": "Swimming - Race Simulation", "duration": 75, "intensity_zone": "Z3"},
        {"type": "Cycling - Race Simulation Ride", "duration": 300, "intensity_zone": "Z3"},
        {"type": "Running - Race Pace Run", "duration": 60, "intensity_zone": "Z4"},
        {"type": "Swimming - Continuous", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Cycling - Threshold Ride", "duration": 75, "intensity_zone": "Z4"},
        {"type": "Running - Long Run", "duration": 165, "intensity_zone": "Z2"},
    ]},
    {"week": 25, "sessions": [
        {"type": "Swimming - Race Simulation", "duration": 80, "intensity_zone": "Z3"},
        {"type": "Cycling - Race Simulation Ride", "duration": 300, "intensity_zone": "Z3"},
        {"type": "Running - Race Pace Run", "duration": 60, "intensity_zone": "Z4"},
        {"type": "Swimming - Continuous", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Brick - Race Simulation", "duration": 210, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 150, "intensity_zone": "Z2"},
    ]},
    # === TAPER: Weeks 26–29 ===
    # Volume drops 50%. Intensity maintained. Freshen legs.
    {"week": 26, "sessions": [
        {"type": "Swimming - Continuous", "duration": 55, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 165, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Swimming - Race Pace Sets", "duration": 45, "intensity_zone": "Z4"},
        {"type": "Cycling - Tempo Ride", "duration": 60, "intensity_zone": "Z3"},
        {"type": "Running - Long Run", "duration": 100, "intensity_zone": "Z2"},
    ]},
    {"week": 27, "sessions": [
        {"type": "Swimming - Continuous", "duration": 50, "intensity_zone": "Z2"},
        {"type": "Cycling - Endurance Ride", "duration": 135, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Swimming - Race Pace Sets", "duration": 40, "intensity_zone": "Z4"},
        {"type": "Cycling - Easy Ride", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Running - Long Run", "duration": 80, "intensity_zone": "Z2"},
    ]},
    {"week": 28, "sessions": [
        {"type": "Swimming - Continuous", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Cycling - Easy Ride", "duration": 90, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 40, "intensity_zone": "Z2"},
        {"type": "Swimming - Race Pace Sets", "duration": 35, "intensity_zone": "Z4"},
        {"type": "Brick - Easy Brick", "duration": 75, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 40, "intensity_zone": "Z2"},
    ]},
    {"week": 29, "sessions": [
        {"type": "Swimming - Easy Swim", "duration": 35, "intensity_zone": "Z1"},
        {"type": "Cycling - Easy Ride", "duration": 60, "intensity_zone": "Z2"},
        {"type": "Running - Easy Run", "duration": 30, "intensity_zone": "Z2"},
        {"type": "Swimming - Activation", "duration": 25, "intensity_zone": "Z2"},
        {"type": "Cycling - Activation Ride", "duration": 45, "intensity_zone": "Z2"},
        {"type": "Running - Strides", "duration": 20, "intensity_zone": "Z3"},
    ]},
    # === RACE WEEK: Week 30 ===
    {"week": 30, "sessions": [
        {"type": "Swimming - Easy Activation", "duration": 25, "intensity_zone": "Z1"},
        {"type": "Cycling - Easy Spin", "duration": 30, "intensity_zone": "Z1"},
        {"type": "Running - Easy Jog", "duration": 20, "intensity_zone": "Z1"},
        {"type": "Swimming - Pre-race Activation", "duration": 20, "intensity_zone": "Z2"},
        {"type": "Race - Ironman 140.6", "duration": 720, "intensity_zone": "Z3"},
    ]},
]
